### ISSUE TITLE
Publish Mac binary?

### ISSUE THREAD

**Issue by lorensr** [percolatestudio/meteor-server-info#5]
I don't need it to work on my Mac dev machine, but I'd like to be able to `meteor add` it. 

```
$ ma percolate:server-info
 => Errors while adding packages:             

While checking for percolate:server-info@0.2.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by zol** [comment]
@lorensr, this looks like a problem with Meteor - `server-info` doesn't contain a binary component, nor does it depend on something whacky :-/

**Comment by zol** [comment]
@lorensr I've run `meteor publish-for-arch percolate:server-info@0.2.3` as instructed by glasser from MDG and it appears to have successfully republished the package.

**Comment by lorensr** [comment]
Thank you, works now!
