### ISSUE TITLE
Gracefully fail outside of ec2

### ISSUE THREAD

**Issue by lorensr** [percolatestudio/meteor-server-info#7]
When I go to `https://myapp.io/info` on a non-ec2 server, the page continuously is loading, and the logs print `ServerInfo: ec2metadata unavailable`. Would be nice if it just showed non-ec2 data.

**Comment by tmeasday** [comment]
Hi @lorensr - I'm pretty sure it does gracefully fail (with that error message). I run it on development quite regularly. I think perhaps the problem is something else?

**Comment by lorensr** [comment]
Works for me in dev too. If anyone comes across this issue using mup + cluster, lmk!
